# Generated by Django 4.2.7 on 2023-11-13 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("launch", "0003_action_time_completed_alter_action_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="project",
        ),
        migrations.AddField(
            model_name="attachment",
            name="content_type",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attachment",
            name="object_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("body", models.TextField()),
                ("content_type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
