# Generated by Django 4.2.7 on 2023-11-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("launch", "0004_remove_attachment_project_attachment_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, upload_to="projects/"),
        ),
    ]
