stages:
  - test
  - build

test:
  image: python:3.12-bullseye
  stage: test
  variables:
    DATABASE_URL: "sqlite://:memory:"
  script:
    - pip install -U pip
    - pip install -r requirements_dev.txt
    - python manage.py collectstatic
    - PYTHONDEVMODE=1 python manage.py test
  only:
    - tags

build:
  stage: build
  image: docker:git
  services:
    - docker:dind
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$CI_COMMIT_TAG .
    - docker push -a $IMAGE_NAME
  only:
    - tags
